Fix rails edge error when generating test application
In particular,

```
LoadError: cannot load such file -- bootsnap/setup
```

produced while booting the generated application, because rails
`config/boot.rb` uses bootsnap by default, but our Gemfile does not
include it.

We don't really need bootsnap, so skip it.